### PR TITLE
Fix controllers on routes

### LINKED ISSUE #2: Duplicate controllers
Duplicate controllers on routes for static pages

### PR DESCRIPTION
**Pull request by PaoloDuzioni**
Closes #2

### CODE REVIEW

File: routes.php [hunk 1]
```diff
@@ -7,6 +7,6 @@
 Route::get('/', 'Home@index');
 
 // Static Pages
-Route::get('/', 'Home@index');
-Route::get('/', 'Home@index');
-Route::get('/', 'Home@index');
\ No newline at end of file
+Route::get('/contacts', 'StaticPage@contacts');
```
Comment (PaoloDuzioni) [inline routes.php:10]: Nice idea the unique controller for the static pages
